### ISSUE TITLE
Disable FastClick on iOS 8

### ISSUE THREAD

**Issue by matthew-andrews** [ftlabs/fastclick#262]
As it's not longer needed (when appropriate meta tags are there)

**Comment by KJTsanaktsidis** [comment]
We found that this issue was causing double clicks to be triggered on our labels (because we hacked fastclick to not needclick on labels). We found adding some code similar to the following to fastclick where the event was being dispatched helped:

```javascript
var clickListener = function (ev) {
    if (!ev.forwardedTouchEvent) {
        ev.preventwindoDefault();
        ev.stopPropagation();
        return false;
    }
};
targetElement.addEventListener('click', clickListener);
setTimeout(function(){
    targetElement.removeEventListener('click', clickListener);
}, 310);
event.preventDefault();
this.sendClick(targetLabel, event);
```

Might it be worth doing something similar in fastclick?
