### ISSUE TITLE
Explicitly define FastClick for JS concat?

### ISSUE THREAD

**Issue by sgarbesi** [ftlabs/fastclick#281]
I'm trying to a concat a set of vendor files and I can't use FastClick without modifying the source due to the following error:

```
Uncaught Error: Mismatched anonymous define() module: function (){"use strict";return FastClick}
```

**Any chance that this:**

``` javascript
    // AMD. Register as an anonymous module.
    define(function() {
        'use strict';
        return FastClick;
    });
```

**Can become this?**

``` javascript
    // AMD. Register as an anonymous module.
    define('FastClick', [], function() {
        'use strict';
        return FastClick;
    });
```

**Comment by patrickkunka** [comment]
I was having some issues today getting r.js to recognise FastClick's UMD declaration so that it could dynamically insert the module name.

I realised the reason why this was happening was to do with a slight variation in the declaration syntax, the I assume meant that it failed r.js's regex pattern (via gulp-amd-optimize).

Not working:
```javascript
if (typeof define === 'function' && typeof define.amd === 'object' && define.amd) {

    // AMD. Register as an anonymous module.
    define(function() {
        return FastClick;
    });
} else if (typeof module !== 'undefined' && module.exports) {
    module.exports = FastClick.attach;
    module.exports.FastClick = FastClick;
} else {
    window.FastClick = FastClick;
}
```

Working:
```
if (typeof define === 'function' && define.amd) {

    // AMD. Register as an anonymous module.
    define(function() {
        return FastClick;
    });
} else if (typeof module !== 'undefined' && module.exports) {
    module.exports = FastClick.attach;
    module.exports.FastClick = FastClick;
} else {
    window.FastClick = FastClick;
}
```

To summarise, removing the additional type-checking on the define.amd, meant that r.js was able to recognise the UMD declaration correctly and insert the module name for concatenation.
